# Generated by Django 5.2.8 on 2025-11-28 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('drf_stripe', '0003_price_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='billing_account_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_account_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='drf_stripe.stripeuser'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['billing_account_content_type', 'billing_account_object_id', 'status'], name='drf_stripe__billing_07dc8e_idx'),
        ),
    ]
